module.exports = [
  {
    ignores: ["node_modules/**", "www/**"],
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        // Browser globals
        document: "readonly",
        window: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        requestAnimationFrame: "readonly",
        fetch: "readonly",
        AudioContext: "readonly",
        webkitAudioContext: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        URL: "readonly",
        confirm: "readonly",
        alert: "readonly",
        location: "readonly",
        history: "readonly",
        // External libs
        lucide: "readonly",
        supabase: "readonly",
        Capacitor: "readonly",
        // App globals
        appState: "writable",
        dbClient: "writable",
        activeTab: "writable",
        trackerDate: "writable",
        reviewTab: "writable",
        reviewMode: "writable",
        reviewWeekId: "writable",
        reviewMonth: "writable",
        reviewYear: "writable",
        careerEditMode: "writable",
        constitutionEditMode: "writable",
        pendingCheckpointCompletion: "writable",
        pendingNorthStarReviewCompletion: "writable",
        APP_CONFIG: "readonly",
        initialMockData: "readonly",
        AI_GOAL_IMPORT_PROMPT_TEMPLATE: "readonly",
        _cachedPrompt: "writable",
        CASCADE_LEVELS: "readonly",
        LEVEL_COLORS: "readonly",
        GOAL_LEVELS: "readonly",
        CHECKPOINT_CONFIRM_TEXT: "readonly",
        WIPE_CONFIRM_TEXT: "readonly",
        DAY_NAMES: "readonly",
        MONTH_NAMES: "readonly",
        MONTH_ABBREVS: "readonly",
        MOOD_LABELS: "readonly",
        TAB_NAMES: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { args: "none" }],
      "no-undef": "error",
      "no-unreachable": "warn",
      "no-constant-condition": "warn",
      "no-duplicate-case": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-semi": "warn",
      "no-redeclare": "error",
      "no-irregular-whitespace": "warn",
      "no-var": "off",
      "prefer-const": "warn",
    },
  },
];
